import React,{useState} from 'react';
import type {AppState,Arrangement,Preferences} from './types';
import {addDays,dateInBeijing,teachingWeek} from './core';
const days=['一','二','三','四','五','六','日'];
const palette=['mint','blue','lavender','peach','rose','sand'];
const color=(a:Arrangement)=>palette[Array.from(a.code).reduce((n,c)=>n+c.charCodeAt(0),0)%palette.length];
function groupDay(items:Arrangement[]){const groups:{start:number;end:number;items:Arrangement[]}[]=[];for(const a of [...items].sort((a,b)=>a.start-b.start)){const last=groups.at(-1);if(last&&a.start<=last.end){last.end=Math.max(last.end,a.end);last.items.push(a);}else groups.push({start:a.start,end:a.end,items:[a]});}return groups;}
interface Props {state:AppState;now:Date;save:(p:Partial<Preferences>)=>void;sync:()=>void;login:()=>void}
export function ScheduleView({state,now,save,sync,login}:Props){
  const [week,setWeek]=useState<number|null>(null),[detail,setDetail]=useState<Arrangement[]|null>(null),[other,setOther]=useState(false);
  const s=state.schedule,p=state.preferences,today=dateInBeijing(now),actual=s?teachingWeek(s.startDate,now):1,selected=week??actual,start=s?addDays(s.startDate,(selected-1)*7):today;
  const active=s?.arrangements.filter(a=>a.weeks.includes(selected))??[];
  const visibleDays=p.showWeekend?days:days.slice(0,5);
  if(!s)return <section className="empty"><div className="empty-calendar">▦</div><h2>从你的真实课表开始</h2><p>自动识别上课周次、教师和教室变化。<br/>登录状态只保留在这台电脑上。</p><button className="primary" onClick={login} disabled={state.sync.status==='syncing'}>登录南京中医药大学教务系统 →</button><small>已有课表将离线保留，登录失效时会提醒你。</small></section>;
  const problem=state.sync.status==='error'||state.sync.status==='login';
  return <section className="schedule-view">
    <div className="compactbar">
      <div className="week-summary"><strong>{selected<1?'学期未开始':selected>s.maxWeek?'学期已结束':`第 ${selected} 周`}</strong><span>{start.slice(5).replace('-','.')}–{addDays(start,6).slice(5).replace('-','.')}</span><small>{s.semester}</small></div>
      <div className="week-nav compact"><button aria-label="上一周" disabled={selected<=1} onClick={()=>setWeek(Math.max(1,selected-1))}>‹</button><button onClick={()=>setWeek(null)}>本周</button><button aria-label="下一周" disabled={selected>=s.maxWeek} onClick={()=>setWeek(Math.min(s.maxWeek,selected+1))}>›</button><select aria-label="选择教学周" value={selected>=1&&selected<=s.maxWeek?selected:''} onChange={e=>setWeek(+e.target.value)}>{(selected<1||selected>s.maxWeek)&&<option value="">学期外</option>}{Array.from({length:s.maxWeek},(_,i)=><option key={i} value={i+1}>第 {i+1} 周</option>)}</select></div>
      <div className="compact-actions"><label title="将其他周在此时段上课的课程显示为灰色"><input type="checkbox" checked={p.showInactive} onChange={e=>save({showInactive:e.target.checked})}/>非本周</label><button className={'sync-pill '+state.sync.status} title={`${state.sync.message}；上次成功：${new Date(s.syncedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}`} onClick={sync} disabled={state.sync.status==='syncing'}><i/>{state.sync.status==='syncing'?'核对中':'同步'}</button></div>
    </div>
    {problem&&<div className={'problembar '+state.sync.status}><span>{state.sync.message}</span>{state.sync.status==='login'&&<button onClick={login}>重新登录</button>}<button onClick={sync}>重试</button></div>}
    <div className="calendar-scroll compact-calendar" style={{'--day-count':visibleDays.length} as React.CSSProperties}><div className="calendar-head"><div className="time-label">时间</div>{visibleDays.map((d,i)=><div key={d} className={addDays(start,i)===today?'today':''}><span>周{d}</span></div>)}</div><div className="calendar-body"><div className="time-column">{s.periods.map(t=><div key={t.number} className={'period '+([6,10].includes(t.number)?'break':'')}><b>{String(t.number).padStart(2,'0')}</b><span>{t.start}<br/>{t.end}</span></div>)}</div>{visibleDays.map((d,i)=>{const dayItems=s.arrangements.filter(a=>a.day===i+1&&(p.showInactive||a.weeks.includes(selected)));return <div key={d} className={'day-column '+(addDays(start,i)===today?'today':'')}>
      {s.periods.map(t=><div key={t.number} className={'grid-line '+([6,10].includes(t.number)?'break':'')} style={{gridRow:t.number}}/>)}
      {groupDay(dayItems).map(g=>{const current=g.items.filter(a=>a.weeks.includes(selected)),inactive=g.items.filter(a=>!a.weeks.includes(selected));return <div className="course-group" key={g.start} style={{gridRow:`${g.start} / ${g.end+1}`}}>{current.length?<><div className="current-courses">{current.map(a=><button key={a.id} className={`course ${color(a)} span-${Math.min(3,a.end-a.start+1)}`} onClick={()=>setDetail([a])}><span className="course-time">{a.start}–{a.end} 节</span><strong>{a.name}</strong><span className="room">{a.room||'教室未填写'}</span><span className="teacher">{a.teacher||'教师未填写'}</span><span className="campus">{a.campus||'校区未填写'}</span></button>)}</div>{inactive.length>0&&<button className="inactive-fold" onClick={()=>setDetail(inactive)}>【非本周】{inactive.length} 项 ›</button>}</>:<button className="course inactive" onClick={()=>setDetail(inactive)}><span className="inactive-tag">【非本周】</span>{inactive.slice(0,2).map(a=><React.Fragment key={a.id}><strong>{a.name}</strong><span>{a.weekText}</span></React.Fragment>)}{inactive.length>2&&<span>另有 {inactive.length-2} 项</span>}<span className="inactive-detail">查看完整安排 ›</span></button>}</div>;})}
      </div>;})}</div></div>
    <footer className="compact-footer"><button className="unscheduled" onClick={()=>setOther(true)}><span>▤</span> 未排时间 / 网络课程 <b>{s.unscheduled.length}</b><span>查看全部 ›</span></button><span className="schedule-count">本周 {active.length} 项 · 教务数据本地保存</span></footer>
    {detail&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><section className="modal details" role="dialog" aria-modal="true" aria-label="课程详情" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setDetail(null)}>×</button><div className="eyebrow">教务系统 · 完整课程安排</div><h2>课程详情</h2>{detail.map(a=><article key={a.id}><h3>{a.name}<span className="detail-status">{a.weeks.includes(selected)?'本周上课':'非本周'}</span></h3><dl><dt>上课时间</dt><dd>周{days[a.day-1]} · 第 {a.start}–{a.end} 节 · {s.periods[a.start-1].start}–{s.periods[a.end-1].end}</dd><dt>上课周次</dt><dd>{a.weekText}</dd><dt>地点</dt><dd>{a.campus||'校区未填写'} · {a.room||'教务系统未填写教室'}</dd><dt>授课教师</dt><dd>{a.teacher}</dd><dt>课程代码</dt><dd>{a.code}</dd><dt>班级</dt><dd>{a.classes||'教务系统未填写'}</dd></dl><details><summary>教务原文</summary><pre>{a.raw.join('\n')}</pre></details></article>)}</section></div>}
    {other&&<div className="modal-backdrop" onClick={()=>setOther(false)}><section className="modal details" role="dialog" aria-modal="true" aria-label="未排时间课程" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setOther(false)}>×</button><div className="eyebrow">这些课程也属于你的学期</div><h2>未排时间 / 网络课程</h2><p>没有固定上课时间，不放入周课表网格。</p>{s.unscheduled.map((c,i)=><article key={c.code+i}><h3>{c.name}</h3><pre>{c.raw}</pre></article>)}{!s.unscheduled.length&&<p>教务页面没有列出未排时间课程。</p>}</section></div>}
  </section>;
}
