import React,{useEffect,useMemo,useState} from 'react';
import type {AppState,Preferences,Todo,TodoFilter,TodoInput} from './types';
import {dateInShanghai,matchesFilter,sortTodos} from './todo-core';
const filterLabels:Record<TodoFilter,string>={today:'今天',upcoming:'近期',all:'全部',completed:'已完成'};
const priorityLabels={high:'高',medium:'中',normal:'普通'};
const reminderLabels={none:'不提醒','at-time':'截止时','10m':'提前 10 分钟','1h':'提前 1 小时','1d':'提前 1 天'};
const recurrenceLabels={none:'不重复',daily:'每天',weekly:'每周',monthly:'每月'};
const empty:TodoInput={title:'',notes:'',dueDate:null,dueTime:null,priority:'normal',tags:[],courseCode:null,courseName:null,reminder:'none',recurrence:'none'};
interface Props {state:AppState;now:Date;save:(p:Partial<Preferences>)=>void;create:(p:TodoInput)=>Promise<void>;update:(id:string,p:TodoInput)=>Promise<void>;complete:(id:string,v:boolean)=>Promise<void>;remove:(id:string)=>Promise<void>}
export function TodoView({state,now,save,create,update,complete,remove}:Props){
 const [search,setSearch]=useState(''),[tag,setTag]=useState(''),[quick,setQuick]=useState(''),[editing,setEditing]=useState<Todo|null>(null),[draft,setDraft]=useState<TodoInput>(empty),[error,setError]=useState('');
 const filter=state.preferences.todoFilter,today=dateInShanghai(now);
 const courses=useMemo(()=>{const m=new Map<string,string>();state.schedule?.arrangements.forEach(a=>m.set(a.code,a.name));return [...m].map(([code,name])=>({code,name})).sort((a,b)=>a.name.localeCompare(b.name,'zh-CN'));},[state.schedule]);
 const tags=useMemo(()=>[...new Set(state.todos.flatMap(t=>t.tags))].sort((a,b)=>a.localeCompare(b,'zh-CN')),[state.todos]);
 const shown=sortTodos(state.todos.filter(t=>matchesFilter(t,filter,now)).filter(t=>!tag||t.tags.includes(tag)).filter(t=>!search||`${t.title} ${t.notes} ${t.courseName??''} ${t.tags.join(' ')}`.toLowerCase().includes(search.toLowerCase())),state.preferences.todoSort);
 const counts={today:state.todos.filter(t=>matchesFilter(t,'today',now)).length,upcoming:state.todos.filter(t=>matchesFilter(t,'upcoming',now)).length,all:state.todos.filter(t=>matchesFilter(t,'all',now)).length,completed:state.todos.filter(t=>matchesFilter(t,'completed',now)).length};
 const open=(todo?:Todo)=>{setError('');setEditing(todo??({id:''} as Todo));setDraft(todo?{title:todo.title,notes:todo.notes,dueDate:todo.dueDate,dueTime:todo.dueTime,priority:todo.priority,tags:todo.tags,courseCode:todo.courseCode,courseName:todo.courseName,reminder:todo.reminder,recurrence:todo.recurrence}:{...empty});};
 useEffect(()=>{const focused=state.todos.find(t=>t.id===state.ui.focusTodoId);if(focused)open(focused);},[state.ui.focusTodoId]);
 const run=async(fn:()=>Promise<void>)=>{setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}};
 const quickAdd=()=>run(async()=>{if(!quick.trim())return;await create({...empty,title:quick});setQuick('');});
 const saveDraft=()=>run(async()=>{if(editing?.id)await update(editing.id,draft);else await create(draft);setEditing(null);});
 const dueText=(t:Todo)=>!t.dueDate?'无日期':t.dueDate===today?`今天${t.dueTime?' '+t.dueTime:''}`:t.dueDate<today?`已逾期 · ${t.dueDate.slice(5)}${t.dueTime?' '+t.dueTime:''}`:`${t.dueDate.slice(5)}${t.dueTime?' '+t.dueTime:''}`;
 return <section className="todo-view">
  <aside className="todo-sidebar"><div><h2>我的待办</h2><p>{counts.all} 件未完成</p></div><nav>{(Object.keys(filterLabels) as TodoFilter[]).map(f=><button key={f} className={filter===f?'active':''} onClick={()=>save({todoFilter:f})}><span>{filterLabels[f]}</span><b>{counts[f]}</b></button>)}</nav>{tags.length>0&&<div className="tag-filter"><label>标签</label><button className={!tag?'active':''} onClick={()=>setTag('')}>全部标签</button>{tags.map(x=><button key={x} className={tag===x?'active':''} onClick={()=>setTag(x)}>#{x}</button>)}</div>}</aside>
  <div className="todo-content"><header className="todo-heading"><div><div className="eyebrow">{filter==='today'?today:'本地待办'}</div><h1>{filterLabels[filter]}</h1></div><button className="new-task" onClick={()=>open()}>＋ 新建待办</button></header>
   <div className="quick-add"><button onClick={quickAdd}>＋</button><input aria-label="快速新增待办" value={quick} onChange={e=>setQuick(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')quickAdd();}} placeholder="快速添加待办，按 Enter 保存…"/></div>
   <div className="todo-tools"><input aria-label="搜索待办" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索待办、课程或标签"/><select aria-label="待办排序" value={state.preferences.todoSort} onChange={e=>save({todoSort:e.target.value as Preferences['todoSort']})}><option value="due">按截止时间</option><option value="priority">按优先级</option><option value="created">按创建时间</option></select></div>
   {error&&<div className="todo-error" role="alert">{error}</div>}
   <div className="todo-list">{shown.map(t=>{const currentCourse=t.courseCode?courses.find(c=>c.code===t.courseCode):null;return <article key={t.id} className={`todo-card priority-${t.priority} ${t.completedAt?'done':''}`}><button className="todo-check" aria-label={t.completedAt?'撤销完成':'完成待办'} onClick={()=>run(()=>complete(t.id,!t.completedAt))}>{t.completedAt?'✓':''}</button><button className="todo-main" onClick={()=>open(t)}><strong>{t.title}</strong><div className="todo-meta">{t.courseName&&<span className="course-chip">{t.courseName}{!currentCourse&&' · 已移出课表'}</span>}{t.recurrence!=='none'&&<span>↻ {recurrenceLabels[t.recurrence]}</span>}{t.reminder!=='none'&&<span>◷ {reminderLabels[t.reminder]}</span>}{t.tags.map(x=><span key={x}>#{x}</span>)}</div>{t.notes&&<p>{t.notes}</p>}</button><span className={`todo-due ${t.dueDate&&t.dueDate<today&&!t.completedAt?'overdue':''}`}>{dueText(t)}</span><span className={`priority-label ${t.priority}`}>{priorityLabels[t.priority]}</span><button className="todo-delete" aria-label="删除待办" onClick={()=>{if(confirm(`确定删除“${t.title}”吗？`))run(()=>remove(t.id));}}>×</button></article>;})}{!shown.length&&<div className="todo-empty"><span>✓</span><h3>{filter==='completed'?'还没有已完成的待办':'这里已经清空了'}</h3><p>{search||tag?'换个搜索条件试试':'添加一条待办，给今天一个清晰的开始。'}</p></div>}</div>
  </div>
  {editing&&<div className="modal-backdrop" onClick={()=>setEditing(null)}><section className="modal todo-editor" role="dialog" aria-modal="true" aria-label={editing.id?'编辑待办':'新建待办'} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setEditing(null)}>×</button><div className="eyebrow">{editing.id?'调整任务细节':'记录下一件要做的事'}</div><h2>{editing.id?'编辑待办':'新建待办'}</h2><label>待办内容<input autoFocus maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="例如：完成数据结构课程设计"/></label><label>备注<textarea maxLength={4000} rows={4} value={draft.notes??''} onChange={e=>setDraft({...draft,notes:e.target.value})} placeholder="补充要求、思路或需要准备的材料"/></label><div className="form-grid"><label>截止日期<input type="date" value={draft.dueDate??''} onChange={e=>setDraft({...draft,dueDate:e.target.value||null,dueTime:e.target.value?draft.dueTime:null,reminder:e.target.value?draft.reminder:'none',recurrence:e.target.value?draft.recurrence:'none'})}/></label><label>具体时间<input type="time" disabled={!draft.dueDate} value={draft.dueTime??''} onChange={e=>setDraft({...draft,dueTime:e.target.value||null,reminder:e.target.value?draft.reminder:'none'})}/></label><label>优先级<select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value as TodoInput['priority']})}><option value="normal">普通</option><option value="medium">中</option><option value="high">高</option></select></label><label>关联课程<select value={draft.courseCode??''} onChange={e=>{const c=courses.find(x=>x.code===e.target.value);setDraft({...draft,courseCode:c?.code??null,courseName:c?.name??null});}}><option value="">不关联课程</option>{draft.courseCode&&!courses.some(c=>c.code===draft.courseCode)&&<option value={draft.courseCode}>{draft.courseName}（已移出课表）</option>}{courses.map(c=><option value={c.code} key={c.code}>{c.name}</option>)}</select></label><label>提醒<select disabled={!draft.dueDate||!draft.dueTime} value={draft.reminder} onChange={e=>setDraft({...draft,reminder:e.target.value as TodoInput['reminder']})}>{Object.entries(reminderLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>重复<select disabled={!draft.dueDate} value={draft.recurrence} onChange={e=>setDraft({...draft,recurrence:e.target.value as TodoInput['recurrence']})}>{Object.entries(recurrenceLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><label>标签<input value={(draft.tags??[]).join('，')} onChange={e=>setDraft({...draft,tags:e.target.value.split(/[，,]/).map(x=>x.trim()).filter(Boolean)})} placeholder="用逗号分隔，例如：作业，复习"/></label>{error&&<div className="todo-error" role="alert">{error}</div>}<div className="editor-actions"><button onClick={()=>setEditing(null)}>取消</button><button className="primary" onClick={saveDraft}>保存待办</button></div></section></div>}
 </section>;
}
